# Generated by Django 4.2.23 on 2025-06-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionauditlog',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'voter'], name='elections_v_electio_622a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['vote_hash'], name='elections_v_vote_ha_d66658_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['blockchain_tx_hash'], name='elections_v_blockch_f49c28_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['created_at'], name='elections_v_created_78b272_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter')},
        ),
        migrations.AddIndex(
            model_name='electionresult',
            index=models.Index(fields=['election', 'decryption_status'], name='elections_e_electio_e9fe2c_idx'),
        ),
        migrations.AddIndex(
            model_name='electionauditlog',
            index=models.Index(fields=['election', 'event_type'], name='elections_e_electio_bd7122_idx'),
        ),
        migrations.AddIndex(
            model_name='electionauditlog',
            index=models.Index(fields=['timestamp'], name='elections_e_timesta_b93059_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status', 'start_date'], name='elections_e_status_2b6bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['created_by', 'status'], name='elections_e_created_ca3425_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_type', 'status'], name='elections_e_electio_f4a181_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'order'], name='elections_c_electio_63d2b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'order')},
        ),
    ]
