# Generated by Django 4.2.23 on 2025-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='private_key_lambda',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='private_key_mu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
