# Generated by Django 4.2.23 on 2025-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_private_key_lambda_election_private_key_mu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='private_key_lambda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='private_key_mu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key_g',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key_n',
            field=models.TextField(blank=True, null=True),
        ),
    ]
