# Generated by Django 4.2.23 on 2025-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload candidate profile picture', null=True, upload_to='candidates/'),
        ),
    ]
