# Generated by Django 4.2.23 on 2025-06-26 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_votereligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='National ID can only contain letters, numbers, hyphens, and underscores', regex='^[A-Za-z0-9\\-_]+$')]),
        ),
    ]
