# Generated by Django 4.2.23 on 2025-07-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_alter_voterprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='blockchain_private_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
