# Generated by Django 4.2.23 on 2025-08-03 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voter_blockchain_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
