# Generated by Django 4.2.23 on 2025-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_alter_voterprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='face_registration_completed',
            field=models.BooleanField(default=False),
        ),
    ]
