# Generated by Django 4.2.23 on 2025-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_voter_face_registration_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='face_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
